In [ ]:
# default_exp core

# core

> API details.

In [ ]:
#hide
from nbdev.showdoc import *

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
iris = pd.read_csv("data/iris.csv")
y = pd.Categorical(iris['species']).codes
x_n = iris.columns[:-1]
x = iris[x_n].values
# x_s = (x_s - x_s.mean(axis=0)) / x_s.std(axis=0)

In [ ]:
x.shape

(150, 4)

In [ ]:
# m: number of samples
# n: number of features
# k: number of output labels
m, n = x.shape
k = 3


W = np.zeros(shape=(n,k))
b = np.zeros(shape=(1,k))

# z = XW + b
z = np.dot(x, W) + b


def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)


(150, 4, 3)

In [ ]:
# Test
z1 = np.array([[1, 2, 3], [5, 5, 5]])
softmax(z1)

array([[0.09003057, 0.24472847, 0.66524096],
       [0.33333333, 0.33333333, 0.33333333]])

In [ ]:
probs = softmax(z)
probs.shape

(150, 3)

In [ ]:
y_pred = np.argmax(probs, axis=1)
y_pred.shape

(150,)

In [ ]:
def crossEntropyLoss(probabilities, target):
    """Calculates cross entropy loss for a set of predictions and actual targets.
    
    Args-
        predictions- Probability predictions, as returned by multinomialLogReg function
        target- Actual target values
    Returns- 
        CELoss- Average cross entropy loss
    """
    n_samples = probabilities.shape[0]
    CELoss = 0
    for sample, i in zip(probabilities, target):
        CELoss += -np.log(sample[i])
    CELoss /= n_samples
    return CELoss   

In [ ]:
crossEntropyLoss(probs, y)

1.098612288668108

In [ ]:
# TRAINING
# X: m*n
# W: n*k
# y: m*1

num_iters = 3
lr = 0.01
W = np.zeros((n, k))
b = np.zeros((1, k))


for i in range(num_iters):

    z = np.dot(x, W) + b
    y_probs = softmax(z)

    # calculate lost and gradients
    loss = crossEntropyLoss(y_probs, y)
    # # back prop / gradient calculations
    dW = y_probs.T.dot(x)
    db = np.sum(y_probs, axis=0).reshape(-1,1)

    W -= lr * dW.T   
    b -= lr * db.T

    if i % 1000 == 0:
        print(i, " - ", loss)

0  -  1.098612288668108


In [ ]:
b, W

(array([[-1.5, -1.5, -1.5]]),
 array([[-8.765, -8.765, -8.765],
        [-4.586, -4.586, -4.586],
        [-5.637, -5.637, -5.637],
        [-1.799, -1.799, -1.799]]))